### ISSUE TITLE
Mobile Layout Problems

### ISSUE THREAD

**Issue by LucasGobatto** [LucasGobatto/WeatherApp#32]
## TODO
- [ ] Search bar goes beyond screen edges

![IMG_070F0F43CB7C-1](https://user-images.githubusercontent.com/20744710/95702372-7f5aa380-0c22-11eb-8bab-e31df7dc92dc.jpeg)

- [ ] Date on sidebar is taking two lines
- [ ] Fix names
- [ ] Fix dark blue background
- [ ] Fix Temperature Unit selector

[Screenshot 2020-10-12 at 00.29.47.pdf](https://github.com/LucasGobatto/WeatherApp/files/5362775/Screenshot.2020-10-12.at.00.29.47.pdf)
